-- Criação do banco de dados
CREATE DATABASE MeuBairro;
GO

USE MeuBairro;
GO

-- Tabelas principais
CREATE TABLE USUARIO (
    IdUsuario INT PRIMARY KEY,
    Apelido VARCHAR(50),
    DataNasc DATE,
    Nome VARCHAR(83),
    Sobrenome VARCHAR(83),
    Descricao NVARCHAR(1000),
    Email VARCHAR(255) UNIQUE,
    FotoPerfil VARBINARY(MAX)
);
GO

CREATE TABLE ENDERECO (
    IdEndereco UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Complemento VARCHAR(255),
    FK_COMUM_CPF VARCHAR(11),
    FK_NEGOCIO_IdNegocio INT,
    FK_NEGOCIO_FK_USUARIO_IdUsuario INT,
    FK_NUMERO_IdNumero INT,
    FK_CEP_IdCep INT,
    FK_BAIRRO_IdBairro INT,
    FK_CIDADE_IdCidade INT,
    FK_ESTADO_IdEstado INT
);
GO

CREATE TABLE TELEFONE (
    IdTelefone INT PRIMARY KEY,
    Telefone VARCHAR(20),
    FK_USUARIO_IdUsuario INT
);
GO

CREATE TABLE COMUM (
    CPF VARCHAR(11) PRIMARY KEY,
    FK_USUARIO_IdUsuario INT NOT NULL
);
GO

CREATE TABLE NEGOCIO (
    IdNegocio INT,
    Cnpj VARCHAR(14) UNIQUE NULL,
    FK_USUARIO_IdUsuario INT,
    FK_COMUM_CPF VARCHAR(11),
    FK_COMUM_FK_USUARIO_IdUsuario INT,
    PRIMARY KEY (IdNegocio, FK_USUARIO_IdUsuario)
    FOREIGN KEY (FK_COMUM_CPF) REFERENCES COMUM(CPF)
);
GO

CREATE TABLE FORMACAO_ACADEMICA (
    IdFormacaoAcademica INT PRIMARY KEY,
    Titulo VARCHAR(100),
    Descricao NVARCHAR(255),
    Tipo VARCHAR(50),
    Instituicao VARCHAR(100),
    DataInicio DATE,
    DataConclusao DATE,
    FK_COMUM_CPF VARCHAR(11),
    FK_USUARIO_IdUsuario INT -- Coluna adicionada
);
GO

CREATE TABLE LINK (
    IdLink INT PRIMARY KEY,
    Titulo NVARCHAR(255),
    Link VARCHAR(255),
    FK_USUARIO_IdUsuario INT
);
GO

CREATE TABLE SESSAO (
    IdSessao INT PRIMARY KEY,
    Titulo NVARCHAR(255),
    Video VARBINARY(MAX),
    Descricao NVARCHAR(255),
    FK_CURSO_IdCurso INT
);

CREATE TABLE CURSO (
    IdCurso INT PRIMARY KEY,
    Titulo NVARCHAR(100),
    Categoria VARCHAR(40),
    Valor DECIMAL(10,2),
    FK_USUARIO_IdUsuario INT
); 
GO

CREATE TABLE PRODUTO (
    Descricao NVARCHAR(255),
    Titulo VARCHAR(100),
    Preco DECIMAL(10,2),
    Quantidade INTEGER,
    Categoria VARCHAR(40),
    IdProduto INTEGER PRIMARY KEY,
    FK_NEGOCIO_IdNegocio INTEGER,
    FK_NEGOCIO_FK_USUARIO_IdUsuario INTEGER
);

CREATE TABLE PRODUTO_USUARIO_pede (
    Status VARCHAR(15),
    Valor DECIMAL(10,2),
    fk_USUARIO_IdUsuario INTEGER,
    fk_PRODUTO_IdProduto INTEGER
);

CREATE TABLE SERVICO (
    Titulo VARCHAR(100),
    Horario TIME,
    IdServico INTEGER PRIMARY KEY,
    Categoria VARCHAR(40),
    Descricao NVARCHAR(255),
    Valor DECIMAL(10,2),
    Requisito NVARCHAR(255),
    FK_USUARIO_IdUsuario INTEGER
);

CREATE TABLE USUARIO_SERVICO_contrata (
    Status VARCHAR(15),
    Data DATE,
    Hora TIME,
    Valor DECIMAL(10,2),
    fk_ENDERECO_IdEndereco UNIQUEIDENTIFIER,
    fk_USUARIO_IdUsuario INTEGER,
    fk_SERVICO_IdServico INTEGER
);

CREATE TABLE USUARIO_CURSO_faz (
    Status VARCHAR(15),
    DataInicio DATE,
    DataConclusao DATE,
    fk_USUARIO_IdUsuario INTEGER,
    fk_CURSO_IdCurso INTEGER
);

CREATE TABLE POST (
    IdPost INTEGER PRIMARY KEY,
    Titulo DATE,
    Descricao NVARCHAR(255),
    FK_USUARIO_IdUsuario INTEGER
);

CREATE TABLE COMENTARIO (
    IdComentario INTEGER PRIMARY KEY,
    Mensagem DATE,
    FK_POST_IdPost INTEGER,
    FK_USUARIO_IdUsuario INTEGER
);

CREATE TABLE IMAGEM (
    IdImagem INTEGER PRIMARY KEY,
    Imagem VARBINARY(MAX),
    Descricao NVARCHAR(255),
    FK_USUARIO_IdUsuario INTEGER,
    FK_SERVICO_IdServico INTEGER,
    FK_POST_IdPost INTEGER,
    FK_PRODUTO_IdProduto INTEGER
);

CREATE TABLE ESTADO (
    IdEstado INTEGER PRIMARY KEY,
    Estado CHAR(2)
);
GO

CREATE TABLE CIDADE (
    IdCidade INTEGER PRIMARY KEY,
    Cidade VARCHAR(100)
);
GO

CREATE TABLE BAIRRO (
    Bairro VARCHAR(100),
    IdBairro INTEGER PRIMARY KEY
);
GO

CREATE TABLE CEP (
    IdCep INTEGER PRIMARY KEY,
    Cep VARCHAR (8)
);
GO

CREATE TABLE NUMERO (
    IdNumero INTEGER PRIMARY KEY,
    Numero INTEGER
);
GO

CREATE TABLE AVALIACAO (
    IdAvaliacao INT PRIMARY KEY,
    Nota FLOAT,
    Descricao VARCHAR(255),
    FK_USUARIO_IdUsuario INT,
    FK_ATIVIDADE_IdAtividade INT
);
GO

CREATE TABLE VAGA_SERVICO (
    IdVagaServico INT PRIMARY KEY,
    QtdPessoas INT,
    Titulo NVARCHAR(100),
    Descricao NVARCHAR(255),
    Categoria VARCHAR(50),
    Requisito NVARCHAR(255),
    Hora TIME,
    Valor DECIMAL(10,2),
    Data DATE,
    Status VARCHAR(15),
    FK_USUARIO_IdUsuario INT,
    FK_ENDERECO_IdEndereco UNIQUEIDENTIFIER
);
GO

CREATE TABLE CANDIDATO_candidata (
    IdCandidato INT PRIMARY KEY,
    Requisito VARCHAR(255),
    fk_ATIVIDADE_IdAtividade INT,
    fk_USUARIO_IdUsuario INT,
    fk_VAGA_SERVICO_IdVagaServico INT
);
GO

CREATE TABLE ATIVIDADE (
    Status VARCHAR (15),
    Data DATE,
    Hora TIME,
    Valor DECIMAL(10,2),
    IdAtividade INTEGER PRIMARY KEY
);

CREATE TABLE NEGOCIO_COMUM (
    fk_COMUM_CPF VARCHAR(11),
    fk_COMUM_FK_USUARIO_IdUsuario INT,
    fk_NEGOCIO_IdNegocio INT,
    fk_NEGOCIO_FK_USUARIO_IdUsuario INT
);
GO



CREATE TABLE IMAGEM_CURSO (
    fk_CURSO_IdCurso INT,
    fk_IMAGEM_IdImagem INT
);
GO

-- Restrições (FKs) e regras ON DELETE
ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_COMUM FOREIGN KEY (FK_COMUM_CPF)
    REFERENCES COMUM (CPF) ON DELETE CASCADE;
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_NEGOCIO FOREIGN KEY (FK_NEGOCIO_IdNegocio, FK_NEGOCIO_FK_USUARIO_IdUsuario)
    REFERENCES NEGOCIO (IdNegocio, FK_USUARIO_IdUsuario) ON DELETE SET NULL;
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_NUMERO FOREIGN KEY (FK_NUMERO_IdNumero) REFERENCES NUMERO(IdNumero);
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_CEP FOREIGN KEY (FK_CEP_IdCep) REFERENCES CEP(IdCep);
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_BAIRRO FOREIGN KEY (FK_BAIRRO_IdBairro) REFERENCES BAIRRO(IdBairro);
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_CIDADE FOREIGN KEY (FK_CIDADE_IdCidade) REFERENCES CIDADE(IdCidade);
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_END_ESTADO FOREIGN KEY (FK_ESTADO_IdEstado) REFERENCES ESTADO(IdEstado);
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TEL_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario) ON DELETE CASCADE;
GO

ALTER TABLE COMUM ADD CONSTRAINT FK_COMUM_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario) ON DELETE CASCADE;
GO

ALTER TABLE NEGOCIO ADD CONSTRAINT FK_NEGOCIO_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE NEGOCIO ADD CONSTRAINT FK_NEGOCIO_COMUM FOREIGN KEY (FK_COMUM_CPF) REFERENCES COMUM(CPF);
GO

ALTER TABLE FORMACAO_ACADEMICA ADD CONSTRAINT FK_FA_COMUM FOREIGN KEY (FK_COMUM_CPF) REFERENCES COMUM(CPF);
GO

ALTER TABLE LINK ADD CONSTRAINT FK_LINK_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE CURSO ADD CONSTRAINT FK_CURSO_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE SESSAO ADD CONSTRAINT FK_SESSAO_CURSO FOREIGN KEY (FK_CURSO_IdCurso) REFERENCES CURSO(IdCurso);
GO

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PROD_NEGOCIO FOREIGN KEY (FK_NEGOCIO_IdNegocio, FK_NEGOCIO_FK_USUARIO_IdUsuario) REFERENCES NEGOCIO(IdNegocio, FK_USUARIO_IdUsuario);
GO

ALTER TABLE PRODUTO_USUARIO_pede ADD CONSTRAINT FK_PUP_USUARIO FOREIGN KEY (fk_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE PRODUTO_USUARIO_pede ADD CONSTRAINT FK_PUP_PRODUTO FOREIGN KEY (fk_PRODUTO_IdProduto) REFERENCES PRODUTO(IdProduto);
GO

ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE USUARIO_SERVICO_contrata ADD CONSTRAINT FK_USC_END FOREIGN KEY (fk_ENDERECO_IdEndereco) REFERENCES ENDERECO(IdEndereco);
GO

ALTER TABLE USUARIO_SERVICO_contrata ADD CONSTRAINT FK_USC_USUARIO FOREIGN KEY (fk_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE USUARIO_SERVICO_contrata ADD CONSTRAINT FK_USC_SERVICO FOREIGN KEY (fk_SERVICO_IdServico) REFERENCES SERVICO(IdServico);
GO

ALTER TABLE USUARIO_CURSO_faz ADD CONSTRAINT FK_UCF_USUARIO FOREIGN KEY (fk_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE USUARIO_CURSO_faz ADD CONSTRAINT FK_UCF_CURSO FOREIGN KEY (fk_CURSO_IdCurso) REFERENCES CURSO(IdCurso);
GO

ALTER TABLE POST ADD CONSTRAINT FK_POST_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COM_POST FOREIGN KEY (FK_POST_IdPost) REFERENCES POST(IdPost);
GO

ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COM_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE IMAGEM ADD CONSTRAINT FK_IMG_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE IMAGEM ADD CONSTRAINT FK_IMG_SERVICO FOREIGN KEY (FK_SERVICO_IdServico) REFERENCES SERVICO(IdServico);
GO

ALTER TABLE IMAGEM ADD CONSTRAINT FK_IMG_POST FOREIGN KEY (FK_POST_IdPost) REFERENCES POST(IdPost);
GO

ALTER TABLE IMAGEM ADD CONSTRAINT FK_IMG_PRODUTO FOREIGN KEY (FK_PRODUTO_IdProduto) REFERENCES PRODUTO(IdProduto);
GO

ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVA_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVA_ATIVIDADE FOREIGN KEY (FK_ATIVIDADE_IdAtividade) REFERENCES ATIVIDADE(IdAtividade);
GO

ALTER TABLE VAGA_SERVICO ADD CONSTRAINT FK_VS_USUARIO FOREIGN KEY (FK_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE VAGA_SERVICO ADD CONSTRAINT FK_VS_END FOREIGN KEY (FK_ENDERECO_IdEndereco) REFERENCES ENDERECO(IdEndereco);
GO

ALTER TABLE CANDIDATO_candidata ADD CONSTRAINT FK_CAN_ATIVIDADE FOREIGN KEY (fk_ATIVIDADE_IdAtividade) REFERENCES ATIVIDADE(IdAtividade);
GO

ALTER TABLE CANDIDATO_candidata ADD CONSTRAINT FK_CAN_USUARIO FOREIGN KEY (fk_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO

ALTER TABLE CANDIDATO_candidata ADD CONSTRAINT FK_CAN_VAGA FOREIGN KEY (fk_VAGA_SERVICO_IdVagaServico) REFERENCES VAGA_SERVICO(IdVagaServico);
GO

ALTER TABLE NEGOCIO_COMUM ADD CONSTRAINT FK_NEGOCIO_CPF FOREIGN KEY (fk_COMUM_CPF) REFERENCES COMUM(CPF);
GO

ALTER TABLE NEGOCIO_COMUM ADD CONSTRAINT FK_COMUM_NEGOCIO FOREIGN KEY (fk_NEGOCIO_IdNegocio, fk_NEGOCIO_FK_USUARIO_IdUsuario) REFERENCES NEGOCIO(IdNegocio, FK_USUARIO_IdUsuario);
GO

ALTER TABLE IMAGEM_CURSO ADD CONSTRAINT FK_TEM_CURSO FOREIGN KEY (fk_CURSO_IdCurso) REFERENCES CURSO(IdCurso);
GO

ALTER TABLE IMAGEM_CURSO ADD CONSTRAINT FK_TEM_IMAGEM FOREIGN KEY (fk_IMAGEM_IdImagem) REFERENCES IMAGEM(IdImagem);
GO

ALTER TABLE FORMACAO_ACADEMICA ADD CONSTRAINT FK_FORM_USUARIO FOREIGN KEY (fk_USUARIO_IdUsuario) REFERENCES USUARIO(IdUsuario);
GO
