"""Criando tabela de Presenca

Revision ID: 0cf228b41107
Revises: cad95f1a7ee9
Create Date: 2025-11-14 20:43:39.980106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf228b41107'
down_revision: Union[str, Sequence[str], None] = 'cad95f1a7ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_presenca', sa.DateTime(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presencas')
    # ### end Alembic commands ###
