"""Criando tabela reserva

Revision ID: 1e3817254755
Revises: 925dbf6e57ec
Create Date: 2025-11-24 17:23:52.296162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3817254755'
down_revision: Union[str, Sequence[str], None] = '925dbf6e57ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_acervo', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_reserva', sa.DateTime(), nullable=False),
    sa.Column('data_validade', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervo'], ['acervos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    # ### end Alembic commands ###
