"""Criando tabela de exemplar

Revision ID: 2b3660e37df4
Revises: 54b3f869ddf0
Create Date: 2025-11-23 20:46:06.109983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3660e37df4'
down_revision: Union[str, Sequence[str], None] = '54b3f869ddf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exemplares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acervo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tombo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=False),
    sa.Column('modo_aquisicao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervo'], ['acervos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tombo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exemplares')
    # ### end Alembic commands ###
