"""Criando tabela de tcc

Revision ID: 38538f64bfb6
Revises: 87b60694433b
Create Date: 2025-11-18 20:22:09.834304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38538f64bfb6'
down_revision: Union[str, Sequence[str], None] = '87b60694433b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tccs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acervos', sa.Integer(), nullable=False),
    sa.Column('tipo_publicacao', sa.String(), nullable=False),
    sa.Column('num_pg', sa.Integer(), nullable=False),
    sa.Column('grau_obtido', sa.Integer(), nullable=False),
    sa.Column('instituicao', sa.String(), nullable=False),
    sa.Column('curso', sa.String(), nullable=False),
    sa.Column('data_defesa', sa.Date(), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervos'], ['acervos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tccs')
    # ### end Alembic commands ###
