"""Criando coluna de telefone

Revision ID: 4de8c315c9a3
Revises: 5a3cb8d940cd
Create Date: 2025-11-10 20:48:34.820881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de8c315c9a3'
down_revision: Union[str, Sequence[str], None] = '5a3cb8d940cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('telefone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'telefone')
    # ### end Alembic commands ###
