"""Criando tabela livro

Revision ID: 54b3f869ddf0
Revises: 558c6113f4d8
Create Date: 2025-11-19 21:47:18.444950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b3f869ddf0'
down_revision: Union[str, Sequence[str], None] = '558c6113f4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acervos', sa.Integer(), nullable=False),
    sa.Column('editor', sa.String(), nullable=False),
    sa.Column('tradutor', sa.String(), nullable=False),
    sa.Column('editora', sa.String(), nullable=False),
    sa.Column('num_pg', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervos'], ['acervos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    # ### end Alembic commands ###
