"""Criando tabelas tipo de acervo

Revision ID: 558c6113f4d8
Revises: 38538f64bfb6
Create Date: 2025-11-19 10:41:46.372802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558c6113f4d8'
down_revision: Union[str, Sequence[str], None] = '38538f64bfb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apostilas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acervos', sa.Integer(), nullable=False),
    sa.Column('editor', sa.String(), nullable=False),
    sa.Column('tradutor', sa.String(), nullable=False),
    sa.Column('editora', sa.String(), nullable=False),
    sa.Column('num_pg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervos'], ['acervos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multimeios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acervos', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervos'], ['acervos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acervos', sa.Integer(), nullable=False),
    sa.Column('editor', sa.String(), nullable=False),
    sa.Column('tradutor', sa.String(), nullable=False),
    sa.Column('editora', sa.String(), nullable=False),
    sa.Column('periodicidade', sa.String(), nullable=False),
    sa.Column('issn', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('suplemento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervos'], ['acervos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodicos')
    op.drop_table('multimeios')
    op.drop_table('apostilas')
    # ### end Alembic commands ###
