"""Corrigindo funcionarios

Revision ID: 5a3cb8d940cd
Revises: 32e54e1becbf
Create Date: 2025-11-10 20:04:12.832522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3cb8d940cd'
down_revision: Union[str, Sequence[str], None] = '32e54e1becbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'cep',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('funcionarios', 'numero_residencia',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'numero_residencia',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('funcionarios', 'cep',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
