"""Criando tabelas de Livros e acervo

Revision ID: 87b60694433b
Revises: 0cf228b41107
Create Date: 2025-11-18 18:52:24.335170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b60694433b'
down_revision: Union[str, Sequence[str], None] = '0cf228b41107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acervos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('sub_titulo', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('cidade_publicacao', sa.String(), nullable=False),
    sa.Column('area_conhecimento', sa.String(), nullable=False),
    sa.Column('imagem', sa.String(), nullable=False),
    sa.Column('idioma', sa.String(), nullable=False),
    sa.Column('cdd', sa.String(), nullable=False),
    sa.Column('cdu', sa.String(), nullable=False),
    sa.Column('pha', sa.String(), nullable=False),
    sa.Column('cutter', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['autores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acervos')
    op.drop_table('autores')
    # ### end Alembic commands ###
