"""Criando tabela Emprestimo

Revision ID: 925dbf6e57ec
Revises: 2b3660e37df4
Create Date: 2025-11-23 21:40:02.181854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925dbf6e57ec'
down_revision: Union[str, Sequence[str], None] = '2b3660e37df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_exemplar', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tempo_atraso', sa.DateTime(), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_exemplar'], ['exemplares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimos')
    # ### end Alembic commands ###
