"""Criando tabela Lista de Desejo

Revision ID: 9de657d6d7aa
Revises: db5315bc5d52
Create Date: 2025-11-24 18:37:16.428698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de657d6d7aa'
down_revision: Union[str, Sequence[str], None] = 'db5315bc5d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listas_desejos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_acervo', sa.Integer(), nullable=False),
    sa.Column('data_adicionado', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_acervo'], ['acervos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listas_desejos')
    # ### end Alembic commands ###
