"""Removendo Atributo Nome da tabela Exemplar

Revision ID: afd988fa1db1
Revises: 9de657d6d7aa
Create Date: 2025-12-02 22:48:19.052993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd988fa1db1'
down_revision: Union[str, Sequence[str], None] = '9de657d6d7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exemplares', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exemplares', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
