"""Criando tabela de cursos e tabela associativa curso_alunos

Revision ID: cad95f1a7ee9
Revises: eb5becbee1e8
Create Date: 2025-11-14 11:30:43.383971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cad95f1a7ee9'
down_revision: Union[str, Sequence[str], None] = 'eb5becbee1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    turno_enum = postgresql.ENUM('manha', 'tarde', 'noite', name='turnoenum', create_type=False) # [!code focus]
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('periodo', turno_enum, nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('instituicao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos_cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('ra', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos_cursos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
