"""Criando tabela avalicao

Revision ID: db5315bc5d52
Revises: 1e3817254755
Create Date: 2025-11-24 18:07:06.583491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5315bc5d52'
down_revision: Union[str, Sequence[str], None] = '1e3817254755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_acervo', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_acervo'], ['acervos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
